# - job:
#     name: "{{itrust_fuzzer_job_name}}"
#     scm: 
#       - git: 
#           url: git@github.ncsu.edu:sbajaj/{{ itrust_test_dir }}.git
#           branches: 
#             - origin/fuzzer
#             - ${sha1}
#     triggers:
#       - pollscm:
#           cron: "" 
#     builders:
#       - shell: 'cd /var/lib/jenkins/jobs/{{itrust_fuzzer_job_name}}/workspace/{{ itrust_test_dir }}/iTrust2 && sudo mvn -f pom-data.xml process-test-classes && sudo mvn clean test verify checkstyle:checkstyle'
     
- job:
    name: "{{iTrust_fuzzer_job}}"
    description: 'iTrust Fuzz test'
    project-type: freestyle
    builders:
      - shell: 'cd /var/lib/jenkins/jobs/{{iTrust_fuzzer_job}}/workspace/ && sudo git clone {{ itrust_test_dir }}'
      - shell: 'sudo cp /var/lib/jenkins/jobs/{{iTrust_fuzzer_job}}/workspace/Testing/iTrust2/src/main/java/db.properties.template /var/lib/jenkins/jobs/{{iTrust_fuzzer_job}}/workspace/Testing/iTrust2/src/main/java/db.properties'
      - shell: 'sudo cp /var/lib/jenkins/jobs/{{iTrust_fuzzer_job}}/workspace/Testing/iTrust2/src/main/java/email.properties.template /var/lib/jenkins/jobs/{{iTrust_fuzzer_job}}/workspace/Testing/iTrust2/src/main/java/email.properties'
      - shell: 'cd /var/lib/jenkins/jobs/{{iTrust_fuzzer_job}}/workspace/Testing/iTrust2 && sudo mvn -f pom-data.xml process-test-classes && sudo mvn clean test verify checkstyle:checkstyle || true'
    publishers:
      - jacoco:
          exec-pattern: '**/target/coverage-reports/**.exec'
          update-build-status: true
          targets:
            - instruction:
                healthy: 50
                unhealthy: 10
