---
  - name: add repo for java 8
    apt_repository: repo='ppa:webupd8team/java' state=present
    become: yes

  - name: Update APT-GET
    shell: apt-get update
    become: true

  - name: Agree to Oracle license
    debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
    become: yes

  - name: install java 8
    apt:  name=openjdk-8-jdk state=latest update-cache=yes force=yes
    sudo: yes

  - name: Update apt-get
    action: apt update_cache=yes
    become: true


